[Fri Sep 16 16:28:06.577838 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800] mod_wsgi (pid=30451): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Fri Sep 16 16:28:06.577906 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800] mod_wsgi (pid=30451): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Fri Sep 16 16:28:06.577930 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800] Traceback (most recent call last):
[Fri Sep 16 16:28:06.577951 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Fri Sep 16 16:28:06.578000 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800]     from app import app as application
[Fri Sep 16 16:28:06.578011 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800]   File "/var/www/api/app.py", line 19, in <module>
[Fri Sep 16 16:28:06.578042 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800]     api.add_resource(searchProject, 'searchProject')
[Fri Sep 16 16:28:06.578050 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800]   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 396, in add_resource
[Fri Sep 16 16:28:06.578207 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800]     self._register_view(self.app, resource, *urls, **kwargs)
[Fri Sep 16 16:28:06.578268 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800]   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 461, in _register_view
[Fri Sep 16 16:28:06.578285 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800]     app.add_url_rule(rule, view_func=resource_func, **kwargs)
[Fri Sep 16 16:28:06.578292 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 62, in wrapper_func
[Fri Sep 16 16:28:06.578674 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800]     return f(self, *args, **kwargs)
[Fri Sep 16 16:28:06.578688 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 976, in add_url_rule
[Fri Sep 16 16:28:06.578705 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800]     rule = self.url_rule_class(rule, methods=methods, **options)
[Fri Sep 16 16:28:06.578711 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800]   File "/usr/local/lib/python2.7/dist-packages/werkzeug/routing.py", line 599, in __init__
[Fri Sep 16 16:28:06.579084 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800]     raise ValueError('urls must start with a leading slash')
[Fri Sep 16 16:28:06.579105 2016] [:error] [pid 30451:tid 140329388001024] [client 122.176.191.88:51800] ValueError: urls must start with a leading slash
[Fri Sep 16 17:27:28.522888 2016] [:error] [pid 31951:tid 139833053734656] [client 122.176.191.88:52440] mod_wsgi (pid=31951): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Fri Sep 16 17:27:28.523042 2016] [:error] [pid 31951:tid 139833053734656] [client 122.176.191.88:52440] mod_wsgi (pid=31951): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Fri Sep 16 17:27:28.523328 2016] [:error] [pid 31951:tid 139833053734656] [client 122.176.191.88:52440] Traceback (most recent call last):
[Fri Sep 16 17:27:28.523360 2016] [:error] [pid 31951:tid 139833053734656] [client 122.176.191.88:52440]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Fri Sep 16 17:27:28.523420 2016] [:error] [pid 31951:tid 139833053734656] [client 122.176.191.88:52440]     from app import app as application
[Fri Sep 16 17:27:28.523431 2016] [:error] [pid 31951:tid 139833053734656] [client 122.176.191.88:52440]   File "/var/www/api/app.py", line 9, in <module>
[Fri Sep 16 17:27:28.523477 2016] [:error] [pid 31951:tid 139833053734656] [client 122.176.191.88:52440]     from projects import *
[Fri Sep 16 17:27:28.523487 2016] [:error] [pid 31951:tid 139833053734656] [client 122.176.191.88:52440]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Fri Sep 16 17:27:28.523510 2016] [:error] [pid 31951:tid 139833053734656] [client 122.176.191.88:52440]     from search import *
[Fri Sep 16 17:27:28.523552 2016] [:error] [pid 31951:tid 139833053734656] [client 122.176.191.88:52440]   File "/var/www/api/projects/search.py", line 16
[Fri Sep 16 17:27:28.523557 2016] [:error] [pid 31951:tid 139833053734656] [client 122.176.191.88:52440]     if data:
[Fri Sep 16 17:27:28.523559 2016] [:error] [pid 31951:tid 139833053734656] [client 122.176.191.88:52440]     ^
[Fri Sep 16 17:27:28.523562 2016] [:error] [pid 31951:tid 139833053734656] [client 122.176.191.88:52440] IndentationError: unexpected indent
[Fri Sep 16 17:28:26.135704 2016] [:error] [pid 32059:tid 140147911804672] [client 122.176.191.88:52445] mod_wsgi (pid=32059): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Fri Sep 16 17:28:26.135768 2016] [:error] [pid 32059:tid 140147911804672] [client 122.176.191.88:52445] mod_wsgi (pid=32059): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Fri Sep 16 17:28:26.135793 2016] [:error] [pid 32059:tid 140147911804672] [client 122.176.191.88:52445] Traceback (most recent call last):
[Fri Sep 16 17:28:26.135817 2016] [:error] [pid 32059:tid 140147911804672] [client 122.176.191.88:52445]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Fri Sep 16 17:28:26.135880 2016] [:error] [pid 32059:tid 140147911804672] [client 122.176.191.88:52445]     from app import app as application
[Fri Sep 16 17:28:26.135891 2016] [:error] [pid 32059:tid 140147911804672] [client 122.176.191.88:52445]   File "/var/www/api/app.py", line 9, in <module>
[Fri Sep 16 17:28:26.135926 2016] [:error] [pid 32059:tid 140147911804672] [client 122.176.191.88:52445]     from projects import *
[Fri Sep 16 17:28:26.135935 2016] [:error] [pid 32059:tid 140147911804672] [client 122.176.191.88:52445]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Fri Sep 16 17:28:26.135956 2016] [:error] [pid 32059:tid 140147911804672] [client 122.176.191.88:52445]     from search import *
[Fri Sep 16 17:28:26.135991 2016] [:error] [pid 32059:tid 140147911804672] [client 122.176.191.88:52445]   File "/var/www/api/projects/search.py", line 16
[Fri Sep 16 17:28:26.135996 2016] [:error] [pid 32059:tid 140147911804672] [client 122.176.191.88:52445]     if data:
[Fri Sep 16 17:28:26.135999 2016] [:error] [pid 32059:tid 140147911804672] [client 122.176.191.88:52445]     ^
[Fri Sep 16 17:28:26.136002 2016] [:error] [pid 32059:tid 140147911804672] [client 122.176.191.88:52445] IndentationError: unexpected indent
[Fri Sep 16 17:29:24.659097 2016] [:error] [pid 32188:tid 140541477119744] [client 122.176.191.88:52450] mod_wsgi (pid=32188): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Fri Sep 16 17:29:24.659156 2016] [:error] [pid 32188:tid 140541477119744] [client 122.176.191.88:52450] mod_wsgi (pid=32188): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Fri Sep 16 17:29:24.659182 2016] [:error] [pid 32188:tid 140541477119744] [client 122.176.191.88:52450] Traceback (most recent call last):
[Fri Sep 16 17:29:24.659207 2016] [:error] [pid 32188:tid 140541477119744] [client 122.176.191.88:52450]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Fri Sep 16 17:29:24.659268 2016] [:error] [pid 32188:tid 140541477119744] [client 122.176.191.88:52450]     from app import app as application
[Fri Sep 16 17:29:24.659279 2016] [:error] [pid 32188:tid 140541477119744] [client 122.176.191.88:52450]   File "/var/www/api/app.py", line 9, in <module>
[Fri Sep 16 17:29:24.659315 2016] [:error] [pid 32188:tid 140541477119744] [client 122.176.191.88:52450]     from projects import *
[Fri Sep 16 17:29:24.659342 2016] [:error] [pid 32188:tid 140541477119744] [client 122.176.191.88:52450]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Fri Sep 16 17:29:24.659367 2016] [:error] [pid 32188:tid 140541477119744] [client 122.176.191.88:52450]     from search import *
[Fri Sep 16 17:29:24.659410 2016] [:error] [pid 32188:tid 140541477119744] [client 122.176.191.88:52450]   File "/var/www/api/projects/search.py", line 17
[Fri Sep 16 17:29:24.659415 2016] [:error] [pid 32188:tid 140541477119744] [client 122.176.191.88:52450]     for item in data:
[Fri Sep 16 17:29:24.659417 2016] [:error] [pid 32188:tid 140541477119744] [client 122.176.191.88:52450]       ^
[Fri Sep 16 17:29:24.659420 2016] [:error] [pid 32188:tid 140541477119744] [client 122.176.191.88:52450] IndentationError: expected an indented block
[Sun Sep 18 23:14:04.856239 2016] [core:error] [pid 5462:tid 139852758562560] [client 89.163.133.20:53362] AH00126: Invalid URI in request GET <title>phpMyAdmin HTTP/1.1
[Sun Sep 25 06:12:11.098350 2016] [core:error] [pid 28521:tid 140620291811072] [client 95.131.24.212:58332] AH00135: Invalid method in request TJPK / HTTP/1.1
[Fri Sep 30 14:16:52.391132 2016] [core:error] [pid 23245:tid 139869158336256] [client 169.229.3.91:35532] AH00135: Invalid method in request \xcd\xfb\xd0Q2\x04/\xae\xf7\xa1\xa3\x9a\xcf\xf2\xd4\xfc\xcfB\xf5\xe8T\xa6\x99\x93\xb0hl\xff\x04'\xd5\xe8\xa7C\x85\xd4\xa4&\xf5xC
[Sat Oct 01 02:41:54.271033 2016] [core:error] [pid 23244:tid 139869116372736] [client 183.129.160.229:54572] AH00135: Invalid method in request test
[Mon Oct 03 23:11:48.314398 2016] [core:error] [pid 21931:tid 139869321500416] [client 208.64.253.242:35565] AH00126: Invalid URI in request GET HTTP/1.1 HTTP/1.1
[Tue Oct 04 17:08:24.129415 2016] [core:error] [pid 21931:tid 139869313107712] [client 183.129.160.229:50851] AH00135: Invalid method in request test
[Thu Oct 06 23:01:31.830382 2016] [core:error] [pid 21931:tid 139869233870592] [client 183.129.160.229:50960] AH00135: Invalid method in request test
[Fri Oct 07 02:54:08.471056 2016] [core:error] [pid 21931:tid 139869200299776] [client 183.129.160.229:47235] AH00135: Invalid method in request test
[Tue Oct 11 07:46:42.937017 2016] [core:error] [pid 20931:tid 139869166728960] [client 183.129.160.229:37145] AH00135: Invalid method in request test
[Fri Oct 14 04:53:28.128833 2016] [core:error] [pid 12489:tid 140446269388544] [client 201.172.58.73:38588] AH00126: Invalid URI in request GET /../../../../../../../mnt/mtd/qt HTTP/1.0
[Fri Oct 14 11:30:56.060437 2016] [:error] [pid 12489:tid 140446252603136] [client 122.162.116.250:50466] mod_wsgi (pid=12489): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module., referer: http://127.0.0.1:8080/
[Fri Oct 14 11:30:56.060494 2016] [:error] [pid 12489:tid 140446252603136] [client 122.162.116.250:50466] mod_wsgi (pid=12489): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'., referer: http://127.0.0.1:8080/
[Fri Oct 14 11:30:56.060554 2016] [:error] [pid 12489:tid 140446252603136] [client 122.162.116.250:50466] Traceback (most recent call last):, referer: http://127.0.0.1:8080/
[Fri Oct 14 11:30:56.060579 2016] [:error] [pid 12489:tid 140446252603136] [client 122.162.116.250:50466]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>, referer: http://127.0.0.1:8080/
[Fri Oct 14 11:30:56.060632 2016] [:error] [pid 12489:tid 140446252603136] [client 122.162.116.250:50466]     from app import app as application, referer: http://127.0.0.1:8080/
[Fri Oct 14 11:30:56.060642 2016] [:error] [pid 12489:tid 140446252603136] [client 122.162.116.250:50466]   File "/var/www/api/app.py", line 20, in <module>, referer: http://127.0.0.1:8080/
[Fri Oct 14 11:30:56.060678 2016] [:error] [pid 12489:tid 140446252603136] [client 122.162.116.250:50466]     api.add_resorce(imageUpload, '/imageUpload'), referer: http://127.0.0.1:8080/
[Fri Oct 14 11:30:56.060696 2016] [:error] [pid 12489:tid 140446252603136] [client 122.162.116.250:50466] AttributeError: 'Api' object has no attribute 'add_resorce', referer: http://127.0.0.1:8080/
[Sat Oct 15 09:12:09.276113 2016] [core:error] [pid 15536:tid 139861918971648] [client 183.129.160.229:54169] AH00135: Invalid method in request test
[Mon Oct 17 19:33:15.446796 2016] [:error] [pid 715:tid 139713392695040] [client 182.68.25.154:62697] mod_wsgi (pid=715): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module., referer: http://127.0.0.1:8080/
[Mon Oct 17 19:33:15.446865 2016] [:error] [pid 715:tid 139713392695040] [client 182.68.25.154:62697] mod_wsgi (pid=715): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'., referer: http://127.0.0.1:8080/
[Mon Oct 17 19:33:15.446897 2016] [:error] [pid 715:tid 139713392695040] [client 182.68.25.154:62697] Traceback (most recent call last):, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:33:15.446925 2016] [:error] [pid 715:tid 139713392695040] [client 182.68.25.154:62697]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:33:15.446987 2016] [:error] [pid 715:tid 139713392695040] [client 182.68.25.154:62697]     from app import app as application, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:33:15.446998 2016] [:error] [pid 715:tid 139713392695040] [client 182.68.25.154:62697]   File "/var/www/api/app.py", line 6, in <module>, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:33:15.447032 2016] [:error] [pid 715:tid 139713392695040] [client 182.68.25.154:62697]     from knowledgeBase import *, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:33:15.447042 2016] [:error] [pid 715:tid 139713392695040] [client 182.68.25.154:62697]   File "/var/www/api/knowledgeBase/__init__.py", line 4, in <module>, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:33:15.447066 2016] [:error] [pid 715:tid 139713392695040] [client 182.68.25.154:62697]     from testupload import *, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:33:15.447279 2016] [:error] [pid 715:tid 139713392695040] [client 182.68.25.154:62697]   File "/var/www/api/knowledgeBase/testupload.py", line 15, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:33:15.447286 2016] [:error] [pid 715:tid 139713392695040] [client 182.68.25.154:62697]     try:, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:33:15.447289 2016] [:error] [pid 715:tid 139713392695040] [client 182.68.25.154:62697]     ^, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:33:15.447293 2016] [:error] [pid 715:tid 139713392695040] [client 182.68.25.154:62697] IndentationError: unexpected indent, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:36:43.372085 2016] [:error] [pid 840:tid 139974426998528] [client 182.68.25.154:62747] mod_wsgi (pid=840): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module., referer: http://127.0.0.1:8080/
[Mon Oct 17 19:36:43.372154 2016] [:error] [pid 840:tid 139974426998528] [client 182.68.25.154:62747] mod_wsgi (pid=840): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'., referer: http://127.0.0.1:8080/
[Mon Oct 17 19:36:43.372184 2016] [:error] [pid 840:tid 139974426998528] [client 182.68.25.154:62747] Traceback (most recent call last):, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:36:43.372210 2016] [:error] [pid 840:tid 139974426998528] [client 182.68.25.154:62747]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:36:43.372272 2016] [:error] [pid 840:tid 139974426998528] [client 182.68.25.154:62747]     from app import app as application, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:36:43.372283 2016] [:error] [pid 840:tid 139974426998528] [client 182.68.25.154:62747]   File "/var/www/api/app.py", line 6, in <module>, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:36:43.372316 2016] [:error] [pid 840:tid 139974426998528] [client 182.68.25.154:62747]     from knowledgeBase import *, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:36:43.372326 2016] [:error] [pid 840:tid 139974426998528] [client 182.68.25.154:62747]   File "/var/www/api/knowledgeBase/__init__.py", line 4, in <module>, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:36:43.372363 2016] [:error] [pid 840:tid 139974426998528] [client 182.68.25.154:62747]     from testupload import *, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:36:43.372603 2016] [:error] [pid 840:tid 139974426998528] [client 182.68.25.154:62747]   File "/var/www/api/knowledgeBase/testupload.py", line 15, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:36:43.372612 2016] [:error] [pid 840:tid 139974426998528] [client 182.68.25.154:62747]     try:, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:36:43.372614 2016] [:error] [pid 840:tid 139974426998528] [client 182.68.25.154:62747]     ^, referer: http://127.0.0.1:8080/
[Mon Oct 17 19:36:43.372617 2016] [:error] [pid 840:tid 139974426998528] [client 182.68.25.154:62747] IndentationError: unexpected indent, referer: http://127.0.0.1:8080/
[Tue Oct 18 04:22:35.122182 2016] [core:error] [pid 2039:tid 140347174807296] [client 201.173.37.13:43808] AH00126: Invalid URI in request GET /../../../../../../../mnt/mtd/qt HTTP/1.0
[Tue Oct 18 20:43:47.920035 2016] [core:error] [pid 6163:tid 139679819085568] [client 183.129.160.229:34847] AH00135: Invalid method in request test
[Fri Oct 21 15:27:16.087640 2016] [:error] [pid 22018:tid 139932844680960] [client 122.180.218.48:59756] mod_wsgi (pid=22018): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module., referer: http://127.0.0.1:8080/
[Fri Oct 21 15:27:16.087708 2016] [:error] [pid 22018:tid 139932844680960] [client 122.180.218.48:59756] mod_wsgi (pid=22018): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'., referer: http://127.0.0.1:8080/
[Fri Oct 21 15:27:16.087745 2016] [:error] [pid 22018:tid 139932844680960] [client 122.180.218.48:59756] Traceback (most recent call last):, referer: http://127.0.0.1:8080/
[Fri Oct 21 15:27:16.087781 2016] [:error] [pid 22018:tid 139932844680960] [client 122.180.218.48:59756]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>, referer: http://127.0.0.1:8080/
[Fri Oct 21 15:27:16.087846 2016] [:error] [pid 22018:tid 139932844680960] [client 122.180.218.48:59756]     from app import app as application, referer: http://127.0.0.1:8080/
[Fri Oct 21 15:27:16.087859 2016] [:error] [pid 22018:tid 139932844680960] [client 122.180.218.48:59756]   File "/var/www/api/app.py", line 33, in <module>, referer: http://127.0.0.1:8080/
[Fri Oct 21 15:27:16.087917 2016] [:error] [pid 22018:tid 139932844680960] [client 122.180.218.48:59756]     api.add_resource(addNewUser, '/addUser'), referer: http://127.0.0.1:8080/
[Fri Oct 21 15:27:16.087940 2016] [:error] [pid 22018:tid 139932844680960] [client 122.180.218.48:59756] NameError: name 'addNewUser' is not defined, referer: http://127.0.0.1:8080/
[Sat Oct 22 02:21:04.420305 2016] [core:error] [pid 22248:tid 140038339749632] [client 183.129.160.229:59979] AH00135: Invalid method in request test
[Sat Oct 22 19:05:50.323766 2016] [core:error] [pid 22247:tid 140038432069376] [client 189.219.180.176:47379] AH00126: Invalid URI in request GET /../../../../../../../mnt/mtd/qt HTTP/1.0
[Wed Oct 26 13:13:05.181518 2016] [core:error] [pid 11574:tid 140038331356928] [client 183.129.160.229:44107] AH00135: Invalid method in request test
[Wed Oct 26 18:41:21.864398 2016] [core:error] [pid 11575:tid 140038356535040] [client 201.172.80.51:35251] AH00126: Invalid URI in request GET /../../../../../../../mnt/mtd/qt HTTP/1.0
[Thu Oct 27 15:30:43.990330 2016] [core:error] [pid 11574:tid 140038423676672] [client 183.129.160.229:44297] AH00135: Invalid method in request test
[Sun Oct 30 19:18:24.691260 2016] [core:error] [pid 11575:tid 140038331356928] [client 189.218.125.192:57755] AH00126: Invalid URI in request GET /../../../../../../../mnt/mtd/qt HTTP/1.0
[Thu Nov 03 18:50:13.965023 2016] [core:error] [pid 9741:tid 140038474032896] [client 189.218.192.45:51755] AH00126: Invalid URI in request GET /../../../../../../../mnt/mtd/qt HTTP/1.0
[Tue Nov 08 04:24:15.451659 2016] [core:error] [pid 4716:tid 140038423676672] [client 189.215.138.92:46811] AH00126: Invalid URI in request GET /../../../../../../../mnt/mtd/qt HTTP/1.0
[Tue Nov 08 08:39:46.497624 2016] [core:error] [pid 4716:tid 140038297786112] [client 1.160.23.169:25476] AH00135: Invalid method in request \xcen\xf3\x88\x10d
[Mon Nov 14 15:34:03.330230 2016] [core:error] [pid 25780:tid 140038339749632] [client 183.129.160.229:57010] AH00135: Invalid method in request test
[Thu Nov 17 18:29:08.099670 2016] [core:error] [pid 25780:tid 140038465640192] [client 183.129.160.229:53499] AH00135: Invalid method in request test
[Sun Nov 20 11:49:23.635810 2016] [core:error] [pid 25781:tid 140038457247488] [client 183.129.160.229:57062] AH00135: Invalid method in request test
[Wed Nov 23 00:52:42.825183 2016] [core:error] [pid 28171:tid 140038390105856] [client 183.129.160.229:57666] AH00135: Invalid method in request test
[Thu Dec 08 11:05:31.700414 2016] [:error] [pid 5649:tid 140289662478080] [client 106.210.93.137:53777] mod_wsgi (pid=5649): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module., referer: http://127.0.0.1:8080/
[Thu Dec 08 11:05:31.700461 2016] [:error] [pid 5649:tid 140289662478080] [client 106.210.93.137:53777] mod_wsgi (pid=5649): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'., referer: http://127.0.0.1:8080/
[Thu Dec 08 11:05:31.700488 2016] [:error] [pid 5649:tid 140289662478080] [client 106.210.93.137:53777] Traceback (most recent call last):, referer: http://127.0.0.1:8080/
[Thu Dec 08 11:05:31.700511 2016] [:error] [pid 5649:tid 140289662478080] [client 106.210.93.137:53777]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>, referer: http://127.0.0.1:8080/
[Thu Dec 08 11:05:31.700568 2016] [:error] [pid 5649:tid 140289662478080] [client 106.210.93.137:53777]     from app import app as application, referer: http://127.0.0.1:8080/
[Thu Dec 08 11:05:31.700579 2016] [:error] [pid 5649:tid 140289662478080] [client 106.210.93.137:53777]   File "/var/www/api/app.py", line 7, in <module>, referer: http://127.0.0.1:8080/
[Thu Dec 08 11:05:31.700612 2016] [:error] [pid 5649:tid 140289662478080] [client 106.210.93.137:53777]     from projects import *, referer: http://127.0.0.1:8080/
[Thu Dec 08 11:05:31.700622 2016] [:error] [pid 5649:tid 140289662478080] [client 106.210.93.137:53777]   File "/var/www/api/projects/__init__.py", line 1, in <module>, referer: http://127.0.0.1:8080/
[Thu Dec 08 11:05:31.700645 2016] [:error] [pid 5649:tid 140289662478080] [client 106.210.93.137:53777]     from search import *, referer: http://127.0.0.1:8080/
[Thu Dec 08 11:05:31.700663 2016] [:error] [pid 5649:tid 140289662478080] [client 106.210.93.137:53777] ImportError: No module named search, referer: http://127.0.0.1:8080/
[Thu Dec 08 12:04:18.838946 2016] [:error] [pid 5649:tid 140289654085376] [client 49.249.42.13:23064] mod_wsgi (pid=5649): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Thu Dec 08 12:04:18.839033 2016] [:error] [pid 5649:tid 140289654085376] [client 49.249.42.13:23064] mod_wsgi (pid=5649): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Thu Dec 08 12:04:18.839069 2016] [:error] [pid 5649:tid 140289654085376] [client 49.249.42.13:23064] Traceback (most recent call last):
[Thu Dec 08 12:04:18.839109 2016] [:error] [pid 5649:tid 140289654085376] [client 49.249.42.13:23064]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Thu Dec 08 12:04:18.839160 2016] [:error] [pid 5649:tid 140289654085376] [client 49.249.42.13:23064]     from app import app as application
[Thu Dec 08 12:04:18.839176 2016] [:error] [pid 5649:tid 140289654085376] [client 49.249.42.13:23064]   File "/var/www/api/app.py", line 7, in <module>
[Thu Dec 08 12:04:18.839198 2016] [:error] [pid 5649:tid 140289654085376] [client 49.249.42.13:23064]     from projects import *
[Thu Dec 08 12:04:18.839209 2016] [:error] [pid 5649:tid 140289654085376] [client 49.249.42.13:23064]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Thu Dec 08 12:04:18.839226 2016] [:error] [pid 5649:tid 140289654085376] [client 49.249.42.13:23064]     from search import *
[Thu Dec 08 12:04:18.839283 2016] [:error] [pid 5649:tid 140289654085376] [client 49.249.42.13:23064] ImportError: No module named search
[Thu Dec 08 12:05:37.107243 2016] [:error] [pid 5649:tid 140289645692672] [client 106.51.29.19:23173] mod_wsgi (pid=5649): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Thu Dec 08 12:05:37.107351 2016] [:error] [pid 5649:tid 140289645692672] [client 106.51.29.19:23173] mod_wsgi (pid=5649): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Thu Dec 08 12:05:37.107395 2016] [:error] [pid 5649:tid 140289645692672] [client 106.51.29.19:23173] Traceback (most recent call last):
[Thu Dec 08 12:05:37.107436 2016] [:error] [pid 5649:tid 140289645692672] [client 106.51.29.19:23173]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Thu Dec 08 12:05:37.107492 2016] [:error] [pid 5649:tid 140289645692672] [client 106.51.29.19:23173]     from app import app as application
[Thu Dec 08 12:05:37.107508 2016] [:error] [pid 5649:tid 140289645692672] [client 106.51.29.19:23173]   File "/var/www/api/app.py", line 7, in <module>
[Thu Dec 08 12:05:37.107530 2016] [:error] [pid 5649:tid 140289645692672] [client 106.51.29.19:23173]     from projects import *
[Thu Dec 08 12:05:37.107540 2016] [:error] [pid 5649:tid 140289645692672] [client 106.51.29.19:23173]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Thu Dec 08 12:05:37.107555 2016] [:error] [pid 5649:tid 140289645692672] [client 106.51.29.19:23173]     from search import *
[Thu Dec 08 12:05:37.107585 2016] [:error] [pid 5649:tid 140289645692672] [client 106.51.29.19:23173] ImportError: No module named search
[Thu Dec 08 12:07:13.695445 2016] [:error] [pid 5648:tid 140289612121856] [client 106.51.29.19:23200] mod_wsgi (pid=5648): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Thu Dec 08 12:07:13.695515 2016] [:error] [pid 5648:tid 140289612121856] [client 106.51.29.19:23200] mod_wsgi (pid=5648): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Thu Dec 08 12:07:13.695543 2016] [:error] [pid 5648:tid 140289612121856] [client 106.51.29.19:23200] Traceback (most recent call last):
[Thu Dec 08 12:07:13.695572 2016] [:error] [pid 5648:tid 140289612121856] [client 106.51.29.19:23200]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Thu Dec 08 12:07:13.695636 2016] [:error] [pid 5648:tid 140289612121856] [client 106.51.29.19:23200]     from app import app as application
[Thu Dec 08 12:07:13.695647 2016] [:error] [pid 5648:tid 140289612121856] [client 106.51.29.19:23200]   File "/var/www/api/app.py", line 7, in <module>
[Thu Dec 08 12:07:13.695680 2016] [:error] [pid 5648:tid 140289612121856] [client 106.51.29.19:23200]     from projects import *
[Thu Dec 08 12:07:13.695690 2016] [:error] [pid 5648:tid 140289612121856] [client 106.51.29.19:23200]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Thu Dec 08 12:07:13.695711 2016] [:error] [pid 5648:tid 140289612121856] [client 106.51.29.19:23200]     from search import *
[Thu Dec 08 12:07:13.695731 2016] [:error] [pid 5648:tid 140289612121856] [client 106.51.29.19:23200] ImportError: No module named search
[Thu Dec 08 12:07:39.422004 2016] [:error] [pid 5649:tid 140289637299968] [client 49.249.42.13:23155] mod_wsgi (pid=5649): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Thu Dec 08 12:07:39.422081 2016] [:error] [pid 5649:tid 140289637299968] [client 49.249.42.13:23155] mod_wsgi (pid=5649): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Thu Dec 08 12:07:39.422117 2016] [:error] [pid 5649:tid 140289637299968] [client 49.249.42.13:23155] Traceback (most recent call last):
[Thu Dec 08 12:07:39.422157 2016] [:error] [pid 5649:tid 140289637299968] [client 49.249.42.13:23155]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Thu Dec 08 12:07:39.422209 2016] [:error] [pid 5649:tid 140289637299968] [client 49.249.42.13:23155]     from app import app as application
[Thu Dec 08 12:07:39.422245 2016] [:error] [pid 5649:tid 140289637299968] [client 49.249.42.13:23155]   File "/var/www/api/app.py", line 7, in <module>
[Thu Dec 08 12:07:39.422269 2016] [:error] [pid 5649:tid 140289637299968] [client 49.249.42.13:23155]     from projects import *
[Thu Dec 08 12:07:39.422293 2016] [:error] [pid 5649:tid 140289637299968] [client 49.249.42.13:23155]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Thu Dec 08 12:07:39.422312 2016] [:error] [pid 5649:tid 140289637299968] [client 49.249.42.13:23155]     from search import *
[Thu Dec 08 12:07:39.422345 2016] [:error] [pid 5649:tid 140289637299968] [client 49.249.42.13:23155] ImportError: No module named search
[Thu Dec 08 12:09:23.443283 2016] [:error] [pid 5648:tid 140289578551040] [client 106.51.29.19:23251] mod_wsgi (pid=5648): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Thu Dec 08 12:09:23.443424 2016] [:error] [pid 5648:tid 140289578551040] [client 106.51.29.19:23251] mod_wsgi (pid=5648): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Thu Dec 08 12:09:23.443458 2016] [:error] [pid 5648:tid 140289578551040] [client 106.51.29.19:23251] Traceback (most recent call last):
[Thu Dec 08 12:09:23.443491 2016] [:error] [pid 5648:tid 140289578551040] [client 106.51.29.19:23251]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Thu Dec 08 12:09:23.443536 2016] [:error] [pid 5648:tid 140289578551040] [client 106.51.29.19:23251]     from app import app as application
[Thu Dec 08 12:09:23.443547 2016] [:error] [pid 5648:tid 140289578551040] [client 106.51.29.19:23251]   File "/var/www/api/app.py", line 7, in <module>
[Thu Dec 08 12:09:23.443562 2016] [:error] [pid 5648:tid 140289578551040] [client 106.51.29.19:23251]     from projects import *
[Thu Dec 08 12:09:23.443571 2016] [:error] [pid 5648:tid 140289578551040] [client 106.51.29.19:23251]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Thu Dec 08 12:09:23.443585 2016] [:error] [pid 5648:tid 140289578551040] [client 106.51.29.19:23251]     from search import *
[Thu Dec 08 12:09:23.443611 2016] [:error] [pid 5648:tid 140289578551040] [client 106.51.29.19:23251] ImportError: No module named search
[Thu Dec 08 12:14:49.045474 2016] [:error] [pid 5649:tid 140289628907264] [client 106.51.29.19:21574] mod_wsgi (pid=5649): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Thu Dec 08 12:14:49.045530 2016] [:error] [pid 5649:tid 140289628907264] [client 106.51.29.19:21574] mod_wsgi (pid=5649): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Thu Dec 08 12:14:49.045555 2016] [:error] [pid 5649:tid 140289628907264] [client 106.51.29.19:21574] Traceback (most recent call last):
[Thu Dec 08 12:14:49.045581 2016] [:error] [pid 5649:tid 140289628907264] [client 106.51.29.19:21574]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Thu Dec 08 12:14:49.045618 2016] [:error] [pid 5649:tid 140289628907264] [client 106.51.29.19:21574]     from app import app as application
[Thu Dec 08 12:14:49.045626 2016] [:error] [pid 5649:tid 140289628907264] [client 106.51.29.19:21574]   File "/var/www/api/app.py", line 7, in <module>
[Thu Dec 08 12:14:49.045637 2016] [:error] [pid 5649:tid 140289628907264] [client 106.51.29.19:21574]     from projects import *
[Thu Dec 08 12:14:49.045642 2016] [:error] [pid 5649:tid 140289628907264] [client 106.51.29.19:21574]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Thu Dec 08 12:14:49.045651 2016] [:error] [pid 5649:tid 140289628907264] [client 106.51.29.19:21574]     from search import *
[Thu Dec 08 12:14:49.045673 2016] [:error] [pid 5649:tid 140289628907264] [client 106.51.29.19:21574] ImportError: No module named search
[Thu Dec 08 12:17:12.072060 2016] [:error] [pid 5648:tid 140289738012416] [client 59.89.154.114:10203] mod_wsgi (pid=5648): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Thu Dec 08 12:17:12.072127 2016] [:error] [pid 5648:tid 140289738012416] [client 59.89.154.114:10203] mod_wsgi (pid=5648): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Thu Dec 08 12:17:12.072158 2016] [:error] [pid 5648:tid 140289738012416] [client 59.89.154.114:10203] Traceback (most recent call last):
[Thu Dec 08 12:17:12.072188 2016] [:error] [pid 5648:tid 140289738012416] [client 59.89.154.114:10203]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Thu Dec 08 12:17:12.072234 2016] [:error] [pid 5648:tid 140289738012416] [client 59.89.154.114:10203]     from app import app as application
[Thu Dec 08 12:17:12.072246 2016] [:error] [pid 5648:tid 140289738012416] [client 59.89.154.114:10203]   File "/var/www/api/app.py", line 7, in <module>
[Thu Dec 08 12:17:12.072262 2016] [:error] [pid 5648:tid 140289738012416] [client 59.89.154.114:10203]     from projects import *
[Thu Dec 08 12:17:12.072270 2016] [:error] [pid 5648:tid 140289738012416] [client 59.89.154.114:10203]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Thu Dec 08 12:17:12.072284 2016] [:error] [pid 5648:tid 140289738012416] [client 59.89.154.114:10203]     from search import *
[Thu Dec 08 12:17:12.072309 2016] [:error] [pid 5648:tid 140289738012416] [client 59.89.154.114:10203] ImportError: No module named search
[Thu Dec 08 12:18:17.664961 2016] [:error] [pid 5648:tid 140289704441600] [client 106.51.29.19:21865] mod_wsgi (pid=5648): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Thu Dec 08 12:18:17.665023 2016] [:error] [pid 5648:tid 140289704441600] [client 106.51.29.19:21865] mod_wsgi (pid=5648): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Thu Dec 08 12:18:17.665137 2016] [:error] [pid 5648:tid 140289704441600] [client 106.51.29.19:21865] Traceback (most recent call last):
[Thu Dec 08 12:18:17.665189 2016] [:error] [pid 5648:tid 140289704441600] [client 106.51.29.19:21865]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Thu Dec 08 12:18:17.665411 2016] [:error] [pid 5648:tid 140289704441600] [client 106.51.29.19:21865]     from app import app as application
[Thu Dec 08 12:18:17.665447 2016] [:error] [pid 5648:tid 140289704441600] [client 106.51.29.19:21865]   File "/var/www/api/app.py", line 7, in <module>
[Thu Dec 08 12:18:17.665474 2016] [:error] [pid 5648:tid 140289704441600] [client 106.51.29.19:21865]     from projects import *
[Thu Dec 08 12:18:17.665487 2016] [:error] [pid 5648:tid 140289704441600] [client 106.51.29.19:21865]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Thu Dec 08 12:18:17.665504 2016] [:error] [pid 5648:tid 140289704441600] [client 106.51.29.19:21865]     from search import *
[Thu Dec 08 12:18:17.665535 2016] [:error] [pid 5648:tid 140289704441600] [client 106.51.29.19:21865] ImportError: No module named search
[Thu Dec 08 12:19:48.038703 2016] [:error] [pid 5649:tid 140289612121856] [client 59.89.154.114:10220] mod_wsgi (pid=5649): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Thu Dec 08 12:19:48.038762 2016] [:error] [pid 5649:tid 140289612121856] [client 59.89.154.114:10220] mod_wsgi (pid=5649): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Thu Dec 08 12:19:48.038797 2016] [:error] [pid 5649:tid 140289612121856] [client 59.89.154.114:10220] Traceback (most recent call last):
[Thu Dec 08 12:19:48.038832 2016] [:error] [pid 5649:tid 140289612121856] [client 59.89.154.114:10220]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Thu Dec 08 12:19:48.038884 2016] [:error] [pid 5649:tid 140289612121856] [client 59.89.154.114:10220]     from app import app as application
[Thu Dec 08 12:19:48.038901 2016] [:error] [pid 5649:tid 140289612121856] [client 59.89.154.114:10220]   File "/var/www/api/app.py", line 7, in <module>
[Thu Dec 08 12:19:48.038923 2016] [:error] [pid 5649:tid 140289612121856] [client 59.89.154.114:10220]     from projects import *
[Thu Dec 08 12:19:48.038938 2016] [:error] [pid 5649:tid 140289612121856] [client 59.89.154.114:10220]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Thu Dec 08 12:19:48.038975 2016] [:error] [pid 5649:tid 140289612121856] [client 59.89.154.114:10220]     from search import *
[Thu Dec 08 12:19:48.039010 2016] [:error] [pid 5649:tid 140289612121856] [client 59.89.154.114:10220] ImportError: No module named search
[Thu Dec 08 12:20:10.151561 2016] [:error] [pid 5648:tid 140289595336448] [client 202.83.18.77:50466] mod_wsgi (pid=5648): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Thu Dec 08 12:20:10.151611 2016] [:error] [pid 5648:tid 140289595336448] [client 202.83.18.77:50466] mod_wsgi (pid=5648): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Thu Dec 08 12:20:10.151632 2016] [:error] [pid 5648:tid 140289595336448] [client 202.83.18.77:50466] Traceback (most recent call last):
[Thu Dec 08 12:20:10.151658 2016] [:error] [pid 5648:tid 140289595336448] [client 202.83.18.77:50466]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Thu Dec 08 12:20:10.151728 2016] [:error] [pid 5648:tid 140289595336448] [client 202.83.18.77:50466]     from app import app as application
[Thu Dec 08 12:20:10.151740 2016] [:error] [pid 5648:tid 140289595336448] [client 202.83.18.77:50466]   File "/var/www/api/app.py", line 7, in <module>
[Thu Dec 08 12:20:10.151751 2016] [:error] [pid 5648:tid 140289595336448] [client 202.83.18.77:50466]     from projects import *
[Thu Dec 08 12:20:10.151757 2016] [:error] [pid 5648:tid 140289595336448] [client 202.83.18.77:50466]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Thu Dec 08 12:20:10.151766 2016] [:error] [pid 5648:tid 140289595336448] [client 202.83.18.77:50466]     from search import *
[Thu Dec 08 12:20:10.151787 2016] [:error] [pid 5648:tid 140289595336448] [client 202.83.18.77:50466] ImportError: No module named search
[Thu Dec 08 12:22:41.217316 2016] [:error] [pid 5648:tid 140289729619712] [client 106.51.29.19:22534] mod_wsgi (pid=5648): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Thu Dec 08 12:22:41.217407 2016] [:error] [pid 5648:tid 140289729619712] [client 106.51.29.19:22534] mod_wsgi (pid=5648): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Thu Dec 08 12:22:41.217442 2016] [:error] [pid 5648:tid 140289729619712] [client 106.51.29.19:22534] Traceback (most recent call last):
[Thu Dec 08 12:22:41.217533 2016] [:error] [pid 5648:tid 140289729619712] [client 106.51.29.19:22534]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Thu Dec 08 12:22:41.217587 2016] [:error] [pid 5648:tid 140289729619712] [client 106.51.29.19:22534]     from app import app as application
[Thu Dec 08 12:22:41.217602 2016] [:error] [pid 5648:tid 140289729619712] [client 106.51.29.19:22534]   File "/var/www/api/app.py", line 7, in <module>
[Thu Dec 08 12:22:41.217624 2016] [:error] [pid 5648:tid 140289729619712] [client 106.51.29.19:22534]     from projects import *
[Thu Dec 08 12:22:41.217637 2016] [:error] [pid 5648:tid 140289729619712] [client 106.51.29.19:22534]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Thu Dec 08 12:22:41.217658 2016] [:error] [pid 5648:tid 140289729619712] [client 106.51.29.19:22534]     from search import *
[Thu Dec 08 12:22:41.217691 2016] [:error] [pid 5648:tid 140289729619712] [client 106.51.29.19:22534] ImportError: No module named search
[Thu Dec 08 13:09:01.267010 2016] [:error] [pid 5648:tid 140289712834304] [client 115.117.132.11:12285] mod_wsgi (pid=5648): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Thu Dec 08 13:09:01.267063 2016] [:error] [pid 5648:tid 140289712834304] [client 115.117.132.11:12285] mod_wsgi (pid=5648): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Thu Dec 08 13:09:01.267091 2016] [:error] [pid 5648:tid 140289712834304] [client 115.117.132.11:12285] Traceback (most recent call last):
[Thu Dec 08 13:09:01.267120 2016] [:error] [pid 5648:tid 140289712834304] [client 115.117.132.11:12285]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Thu Dec 08 13:09:01.267176 2016] [:error] [pid 5648:tid 140289712834304] [client 115.117.132.11:12285]     from app import app as application
[Thu Dec 08 13:09:01.267187 2016] [:error] [pid 5648:tid 140289712834304] [client 115.117.132.11:12285]   File "/var/www/api/app.py", line 7, in <module>
[Thu Dec 08 13:09:01.267200 2016] [:error] [pid 5648:tid 140289712834304] [client 115.117.132.11:12285]     from projects import *
[Thu Dec 08 13:09:01.267207 2016] [:error] [pid 5648:tid 140289712834304] [client 115.117.132.11:12285]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Thu Dec 08 13:09:01.267218 2016] [:error] [pid 5648:tid 140289712834304] [client 115.117.132.11:12285]     from search import *
[Thu Dec 08 13:09:01.267241 2016] [:error] [pid 5648:tid 140289712834304] [client 115.117.132.11:12285] ImportError: No module named search
[Thu Dec 08 13:11:12.589933 2016] [:error] [pid 5648:tid 140289696048896] [client 115.117.132.11:10030] mod_wsgi (pid=5648): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Thu Dec 08 13:11:12.590017 2016] [:error] [pid 5648:tid 140289696048896] [client 115.117.132.11:10030] mod_wsgi (pid=5648): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Thu Dec 08 13:11:12.590055 2016] [:error] [pid 5648:tid 140289696048896] [client 115.117.132.11:10030] Traceback (most recent call last):
[Thu Dec 08 13:11:12.590091 2016] [:error] [pid 5648:tid 140289696048896] [client 115.117.132.11:10030]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Thu Dec 08 13:11:12.590138 2016] [:error] [pid 5648:tid 140289696048896] [client 115.117.132.11:10030]     from app import app as application
[Thu Dec 08 13:11:12.590153 2016] [:error] [pid 5648:tid 140289696048896] [client 115.117.132.11:10030]   File "/var/www/api/app.py", line 7, in <module>
[Thu Dec 08 13:11:12.590170 2016] [:error] [pid 5648:tid 140289696048896] [client 115.117.132.11:10030]     from projects import *
[Thu Dec 08 13:11:12.590180 2016] [:error] [pid 5648:tid 140289696048896] [client 115.117.132.11:10030]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Thu Dec 08 13:11:12.590193 2016] [:error] [pid 5648:tid 140289696048896] [client 115.117.132.11:10030]     from search import *
[Thu Dec 08 13:11:12.590221 2016] [:error] [pid 5648:tid 140289696048896] [client 115.117.132.11:10030] ImportError: No module named search
[Thu Dec 08 13:11:25.885388 2016] [:error] [pid 5649:tid 140289595336448] [client 47.31.21.165:34279] mod_wsgi (pid=5649): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Thu Dec 08 13:11:25.885471 2016] [:error] [pid 5649:tid 140289595336448] [client 47.31.21.165:34279] mod_wsgi (pid=5649): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Thu Dec 08 13:11:25.885496 2016] [:error] [pid 5649:tid 140289595336448] [client 47.31.21.165:34279] Traceback (most recent call last):
[Thu Dec 08 13:11:25.885535 2016] [:error] [pid 5649:tid 140289595336448] [client 47.31.21.165:34279]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Thu Dec 08 13:11:25.885581 2016] [:error] [pid 5649:tid 140289595336448] [client 47.31.21.165:34279]     from app import app as application
[Thu Dec 08 13:11:25.885596 2016] [:error] [pid 5649:tid 140289595336448] [client 47.31.21.165:34279]   File "/var/www/api/app.py", line 7, in <module>
[Thu Dec 08 13:11:25.885614 2016] [:error] [pid 5649:tid 140289595336448] [client 47.31.21.165:34279]     from projects import *
[Thu Dec 08 13:11:25.885622 2016] [:error] [pid 5649:tid 140289595336448] [client 47.31.21.165:34279]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Thu Dec 08 13:11:25.885632 2016] [:error] [pid 5649:tid 140289595336448] [client 47.31.21.165:34279]     from search import *
[Thu Dec 08 13:11:25.885653 2016] [:error] [pid 5649:tid 140289595336448] [client 47.31.21.165:34279] ImportError: No module named search
[Thu Dec 08 13:15:24.385062 2016] [:error] [pid 5648:tid 140289687656192] [client 117.96.36.42:55907] mod_wsgi (pid=5648): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Thu Dec 08 13:15:24.385122 2016] [:error] [pid 5648:tid 140289687656192] [client 117.96.36.42:55907] mod_wsgi (pid=5648): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Thu Dec 08 13:15:24.385155 2016] [:error] [pid 5648:tid 140289687656192] [client 117.96.36.42:55907] Traceback (most recent call last):
[Thu Dec 08 13:15:24.385188 2016] [:error] [pid 5648:tid 140289687656192] [client 117.96.36.42:55907]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Thu Dec 08 13:15:24.385240 2016] [:error] [pid 5648:tid 140289687656192] [client 117.96.36.42:55907]     from app import app as application
[Thu Dec 08 13:15:24.385253 2016] [:error] [pid 5648:tid 140289687656192] [client 117.96.36.42:55907]   File "/var/www/api/app.py", line 7, in <module>
[Thu Dec 08 13:15:24.385270 2016] [:error] [pid 5648:tid 140289687656192] [client 117.96.36.42:55907]     from projects import *
[Thu Dec 08 13:15:24.385280 2016] [:error] [pid 5648:tid 140289687656192] [client 117.96.36.42:55907]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Thu Dec 08 13:15:24.385294 2016] [:error] [pid 5648:tid 140289687656192] [client 117.96.36.42:55907]     from search import *
[Thu Dec 08 13:15:24.385320 2016] [:error] [pid 5648:tid 140289687656192] [client 117.96.36.42:55907] ImportError: No module named search
[Thu Dec 08 13:29:27.080021 2016] [:error] [pid 5649:tid 140289586943744] [client 106.216.184.212:7482] mod_wsgi (pid=5649): Target WSGI script '/var/www/api/wsgi/flask.wsgi' cannot be loaded as Python module.
[Thu Dec 08 13:29:27.080098 2016] [:error] [pid 5649:tid 140289586943744] [client 106.216.184.212:7482] mod_wsgi (pid=5649): Exception occurred processing WSGI script '/var/www/api/wsgi/flask.wsgi'.
[Thu Dec 08 13:29:27.080199 2016] [:error] [pid 5649:tid 140289586943744] [client 106.216.184.212:7482] Traceback (most recent call last):
[Thu Dec 08 13:29:27.080245 2016] [:error] [pid 5649:tid 140289586943744] [client 106.216.184.212:7482]   File "/var/www/api/wsgi/flask.wsgi", line 7, in <module>
[Thu Dec 08 13:29:27.080296 2016] [:error] [pid 5649:tid 140289586943744] [client 106.216.184.212:7482]     from app import app as application
[Thu Dec 08 13:29:27.080309 2016] [:error] [pid 5649:tid 140289586943744] [client 106.216.184.212:7482]   File "/var/www/api/app.py", line 7, in <module>
[Thu Dec 08 13:29:27.080328 2016] [:error] [pid 5649:tid 140289586943744] [client 106.216.184.212:7482]     from projects import *
[Thu Dec 08 13:29:27.080338 2016] [:error] [pid 5649:tid 140289586943744] [client 106.216.184.212:7482]   File "/var/www/api/projects/__init__.py", line 1, in <module>
[Thu Dec 08 13:29:27.080353 2016] [:error] [pid 5649:tid 140289586943744] [client 106.216.184.212:7482]     from search import *
[Thu Dec 08 13:29:27.080401 2016] [:error] [pid 5649:tid 140289586943744] [client 106.216.184.212:7482] ImportError: No module named search
